### ISSUE TITLE
[FxTec Pro 1] Keyboard is not recognized by software after upgrading to bookworm

### ISSUE THREAD

**Issue by samzanemesis** [droidian/meta#9]
After upgrading to Bookworm it seems phosh and gnome no longer properly recognizes the keyboard

It can still be used for input, but every text field will open the virtual keyboard even when the keyboard is open, and I can no longer adjust keyboard brighness

**Comment by g7** [comment]
Could you check if you have some other updates to do?

Also, could you please post the output of the following commands:

```
apt policy adaptation-fxtec-pro1
apt policy libinput10
apt policy phosh
apt policy phoc
```

As a bit of context, until I'm happy with the changes to support the keyboard in phosh/phoc, they will stay in a separate repository. These packages are preferred when the `adaptation-fxtec-pro1` package is installed, but due to how the upgrade process works, you might now have the "standard" packages from the Droidian repositories rather than the pro1 specific ones.

If that's the case, doing an update && dist-upgrade again should fix that. Another thing that might have happened is that the adaptation package has been removed for some reason, so in that case you can reinstall that so that repositories and apt pins are put into place again.

**Comment by samzanemesis** [comment]
I have attempted apt reinstall and dpkg-reconfigure on adaptation-fxtec-pro1* and it remains the same

For reference here's the log of my apt policy

```
 droidian@sam-fxtec  ~  apt policy adaptation-fxtec-pro1 && apt policy libinput10 && apt policy phosh && apt policy phoc
adaptation-fxtec-pro1:
  Installed: 21+git20211212000038.23db21b.bookworm.production
  Candidate: 21+git20211212000038.23db21b.bookworm.production
  Version table:
 *** 21+git20211212000038.23db21b.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main amd64 Packages
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
       1002 https://production.repo.droidian.org bookworm/main armhf Packages
        100 /var/lib/dpkg/status
libinput10:
  Installed: 1.19.3-1~git20220219161901.2cff5b9.bookworm.keypad.slide
  Candidate: 1.19.3-1~git20220219161901.2cff5b9.bookworm.keypad.slide
  Version table:
     1.19.3-2 500
        500 https://deb.debian.org/debian bookworm/main arm64 Packages
 *** 1.19.3-1~git20220219161901.2cff5b9.bookworm.keypad.slide 1003
       1002 http://droidian-libinput.repo.droidian.org/bookworm-keypad-slide bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
     1.19.2-1~git20211211221827.88b759d.bookworm.keypad.slide 1003
       1002 http://droidian-libinput.repo.droidian.org/bookworm-keypad-slide bookworm/main arm64 Packages
phosh:
  Installed: 0.15.0-1+droidian0+git20220126215127.26f326f.bookworm.production
  Candidate: 0.15.0-1+droidian0+git20220130233748.079f8cd.bookworm.keypad.slide.lights
  Version table:
     0.15.0-1+droidian0+git20220130233748.079f8cd.bookworm.keypad.slide.lights 1003
       1002 http://droidian-phosh.repo.droidian.org/bookworm-keypad-slide-lights bookworm/main arm64 Packages
 *** 0.15.0-1+droidian0+git20220126215127.26f326f.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
     0.15.0-1 1001
       1001 http://repo.mobian-project.org bookworm/main arm64 Packages
     0.15.0-1~git20220126215157.b626e44.bookworm.keypad.slide.lights 1003
       1002 http://droidian-phosh.repo.droidian.org/bookworm-keypad-slide-lights bookworm/main arm64 Packages
     0.14.1-1+droidian0+git20211208190840.c2942a4.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
     0.14.1-1+deb11+droidian0+git20211208190659.189335a.bookworm.keypad.slide.lights 1003
       1002 http://droidian-phosh.repo.droidian.org/bookworm-keypad-slide-lights bookworm/main arm64 Packages
     0.14.0-1+droidian1+upgrade12+git20211127110726.c59d5bb.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
     0.13.1-2 500
        500 https://deb.debian.org/debian bookworm/main arm64 Packages
phoc:
  Installed: 0.10.0-1+droidian0+git20220111211156.5e0435e.bookworm.production
  Candidate: 0.10.0-1+droidian0+git20220111214614.10694be.bookworm.forward.switch.events
  Version table:
     0.12.0-1 500
        500 https://deb.debian.org/debian bookworm/main arm64 Packages
     0.10.0-1+droidian0+git20220111214614.10694be.bookworm.forward.switch.events 1003
       1002 http://droidian-phoc.repo.droidian.org/bookworm-forward-switch-events bookworm/main arm64 Packages
 *** 0.10.0-1+droidian0+git20220111211156.5e0435e.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
     0.9.0-1+droidian0+upgrade12+git20211106172644.c7e7399.bookworm.production 1002
       1002 https://production.repo.droidian.org bookworm/main arm64 Packages
     0.9.0-1+droidian0+git20211208191146.e62e1cc.bookworm.forward.switch.events 1003
       1002 http://droidian-phoc.repo.droidian.org/bookworm-forward-switch-events bookworm/main arm64 Packages
```

I did notice phosh had an installation candidate, I have done `# apt install phosh=0.15.0-1+droidian0+git20220130233748.079f8cd.bookworm.keypad.slide.lights` but the results are the same

**Comment by g7** [comment]
Have you installed the phoc candidate as well? Both are required, otherwise phosh wouldn't get to know the switch events as they happen.

Theoretically doing `apt dist-upgrade` again should pick those automatically

**Comment by samzanemesis** [comment]
Doing that fixed the issue, keyboard backlight appears correctly and phosh properly detects a hardware keyboard when unfolded, weird how these packages didn't install at first, thank you for the support!

Just a note that the keyboard brightness setting is still missing on the menu, but as binary as it was it is not a big problem
